// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ0tePUcw1g_KqqG74ppUgDOX5R5BjfXs',
    appId: '1:1042051267417:web:c2db807a845a6869ab6a48',
    messagingSenderId: '1042051267417',
    projectId: 'hospital-management-ad0ea',
    authDomain: 'hospital-management-ad0ea.firebaseapp.com',
    storageBucket: 'hospital-management-ad0ea.firebasestorage.app',
    measurementId: 'G-H2QXJBXT80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4l_xTfkO0GwPRrMGqPfJ_QYMztiNwR6w',
    appId: '1:1042051267417:android:843254b839acdb5dab6a48',
    messagingSenderId: '1042051267417',
    projectId: 'hospital-management-ad0ea',
    storageBucket: 'hospital-management-ad0ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLHjOfzHx-iTxXeyHbxreRwYY22s1gXE',
    appId: '1:1042051267417:ios:c70006a1b2a757f6ab6a48',
    messagingSenderId: '1042051267417',
    projectId: 'hospital-management-ad0ea',
    storageBucket: 'hospital-management-ad0ea.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPLHjOfzHx-iTxXeyHbxreRwYY22s1gXE',
    appId: '1:1042051267417:ios:c70006a1b2a757f6ab6a48',
    messagingSenderId: '1042051267417',
    projectId: 'hospital-management-ad0ea',
    storageBucket: 'hospital-management-ad0ea.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ0tePUcw1g_KqqG74ppUgDOX5R5BjfXs',
    appId: '1:1042051267417:web:4a5b3f1987c1a6f5ab6a48',
    messagingSenderId: '1042051267417',
    projectId: 'hospital-management-ad0ea',
    authDomain: 'hospital-management-ad0ea.firebaseapp.com',
    storageBucket: 'hospital-management-ad0ea.firebasestorage.app',
    measurementId: 'G-ZYW1CBD892',
  );
}
